on:
  create:
    tags:
      - v*.*.*
name: Build artifact, Create RELEASE page, and upload artifact to RELEASE page

jobs:
  releaseArtifact:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Printenv
        run: |
          printenv
          mkdir -p out/
          printenv > out/env.txt

      - name: setup Go
        uses: actions/setup-go@v1
        with:
          version: 1.12
        id: go

      - name: Create release page
        env:
          GO111MODULE: on
          GOPATH: /home/runner/work
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          export TAGNAME=$(jq --raw-output .ref "${GITHUB_EVENT_PATH}")
          ${GOPATH}/bin/ghr -n ${TAGNAME} -b "${TAGNAME}" -draft ${TAGNAME} out/env.txt
